artifacts_root: artifacts


data_ingestion:
     root_dir: artifacts/data_ingestion
     source_URL: https://raw.githubusercontent.com/shruti629/textsummarizer/main/summarizer-data.zip
     local_data_file: artifacts/data_ingestion/data.zip
     unzip_dir: artifacts/data_ingestion

